[workspace]
members = [
    "pe-parser",
    "elf-parser",
    "macho-parser",
    "coff-parser",
    "dex-parser",
    "wasm-parser",
    "flat-binary",
    "entropy-rs",
    "str-extract",
    "import-analyzer",
    "yara-lite",
    "backdoor-analyzer",
    "shellcode-analyzer",
    "xrefs",
    "cfg-builder",
    "func-sigs",
    "scanner",
    "desktop-ui",
    "freakre-ir",
    "dataflow",
    "type-propagation",
    "decompiler",
    "project-db",
    "func-finder",
    "type-system",
    "plugins",
    "diffing",
    "sys-plugins",
    "freakre-hash",
    "freakre-config",
    "freakre-patterns",
    "freakre-x86",
    "freakre-script",
    "scripting",
    "symbols",
    "capstone-ffi",
    "ml-detection",
    "emulator-x86",
    "gpu-scan",
    "behavior-detect",
    "script-analyzer",
    "pdf-analyzer",
    "dotnet-analyzer",
    "pyc-parser",
    "firmware-analyzer",
    "memdump-analyzer",
    "freakre-server", "dll-analyzer",
]
exclude = ["fuzz"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "2"
