[package]
name = "freakre-sys-plugins"
version = "0.1.0"
edition = "2021"
description = "Built-in system plugins for FreakRE"

[dependencies]
plugins = { path = "../plugins" }
project-db = { path = "../project-db" }
func-finder = { path = "../func-finder" }
freakre-x86 = { path = "../freakre-x86" }
entropy-rs = { path = "../entropy-rs" }
str-extract = { path = "../str-extract" }
type-system = { path = "../type-system" }
thiserror = { workspace = true }
serde = { workspace = true }
